### ISSUE TITLE
Figure out how to automate the vendor and gazelle of dependabot PRs

### ISSUE THREAD

**Issue by statik** [kindlyops/pipeline-monitor#14]
When dependabot submits a PR updating go.mod and go.sum, we still need to run go mod vendor and gazelle.

A minimal solution would be to configure either dependabot or an action to automatically comment on the PR explaining that this step is needed.

A neato solution would be to add a github action that runs those commands automatically on github PRs that are a) from dependabot and b) update go.mod / go.sum, and commits the new changes to the PR branch.

Then our CI could run to confirm everything still passes.

**Comment by whilp** [comment]
> A neato solution would be to add a github action that runs those commands
automatically on github PRs that are a) from dependabot and b) update
go.mod / go.sum, and commits the new changes to the PR branch.

oh wow yes
