### ISSUE TITLE
Can't trigger GitHub CI run after autocommit

### ISSUE THREAD

**Issue by statik** [kindlyops/pipeline-monitor#33]
When we push a new commit to the repo from the CI run,
that new commit does not trigger a new CI run. This interacts poorly with the 'required checks' feature of GitHub, as there is no CI check status on the top commit and so the merge requires admin override.

**Comment by statik** [comment]
supposedly this can be fixed by using a personal access token with the latest version of checkout and autocommit actions, see https://github.com/stefanzweifel/git-auto-commit-action/issues/43

**Comment by stefanzweifel** [comment]
Saw the linked issue and thought I chip in:

I've now documented how you can use the Action with a personal access token [here](https://github.com/stefanzweifel/git-auto-commit-action#commit-of-this-action-does-not-trigger-a-new-workflow-run).

Hope this works for you ✌️

**Comment by statik** [comment]
@stefanzweifel thank you so much for creating the autocommit action and taking the time to comment here. It is working great now! This really makes my day. 🎉
